# Generated by Django 5.0.6 on 2024-06-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_alter_partidos_barcelona_total_alter_partidos_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidos',
            name='barcelona_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='ganador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='madrid_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
