# Generated by Django 5.0.6 on 2024-06-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_alter_partidos_barcelona_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidos',
            name='barcelona_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='madrid_total',
            field=models.IntegerField(default=0),
        ),
    ]
