# Generated by Django 5.0.6 on 2024-06-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_partidos_barcelona_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predicciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcelona', models.IntegerField()),
                ('empate', models.IntegerField()),
                ('madrid', models.IntegerField()),
            ],
        ),
    ]
