# Generated by Django 5.0.6 on 2024-06-15 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_predicciones_suma'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadioGoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.IntegerField(default=0)),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.estadio')),
            ],
        ),
    ]
